[package]
name = "xender"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-std = "1.10.0"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
druid = "0.8.0"
druid-widget-nursery = "0.1.0"